name: Build and deploy Node.js API to Azure Web App – my-sd-backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies for backend
        # --prefix runs npm inside your /backend folder
        run: npm install --prefix backend

      - name: (Optional) Build backend
        # only if you have a "build" script in backend/package.json
        run: npm run build --prefix backend --if-present

      - name: Zip backend folder
        run: |
          cd backend
          zip -r ../backend-release.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: my-sd-backend         # your App Service name
          package: backend-release.zip     # pointing at your zipped /backend
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1234 }}
